### ISSUE TITLE
After authorizing Tuya for Homey, I get a 'permission deny (Code 1106)' message

### ISSUE THREAD

**Issue by cyrilhendriks** [athombv/com.tuya#135]
### Homey version

2023 Homey Pro

### Tuya app version

1.1.1

### App diagnostics report ID

ea8a9fb4-edc0-48a5-816a-1ca6da4fad55

### Description

After logging in and authorization:
![image](https://github.com/user-attachments/assets/b7f7832f-2c67-42f4-b5f3-89f14bad2c00)

I get the following error message:
![image](https://github.com/user-attachments/assets/ffe88fd4-040c-4039-aca4-7d5f58b8f598)

Since I was using the community Tuya Cloud app, I decided to remove the Tuya account, Cloud account and project, did a full reset of the devices and created a new account with different email address in the Smartlife app.

Unfortunately the error still exists :(

Several Homey restarts, installing the latest test version, etc. didn't help either.

### Device specification

<details>

```json
  { "device": ..., "specifications": ...}
```

</details>

**Comment by nebreg** [comment]
I got the same problem :-(

**Comment by manologiuliani** [comment]
Same problem too

**Comment by manologiuliani** [comment]
1ae8010b-2262-4965-a585-55964f1d8c7d

**Comment by BerndGaykema** [comment]
I got this "code 1106 error" too.

**Comment by MojoDK** [comment]
Same error here :(

**Comment by bobvandevijver** [comment]
This should be resolved with version 1.2.1, which is in testing right now.

**Comment by cyrilhendriks** [comment]
Thank you @bobvandevijver , I can confirm that it indeed works now. :)

**Comment by manologiuliani** [comment]
Not in my case sadly! tried the testing version but still the same error. 577cc2f0-ba1f-4269-846e-a0051f5eb8d2
![IMG_1417](https://github.com/user-attachments/assets/646b1286-a845-4af7-8124-8154620bc660)
![IMG_1416](https://github.com/user-attachments/assets/1c736405-a22c-4398-b2d8-b145bc567013)

**Comment by bobvandevijver** [comment]
@manologiuliani Please don't post on closed issues: if you still experience issue you can open a new ticket. But, be aware that the report you've submitted was not for the app in test, so that would be the reason why it doesn't work for you.
