### ISSUE TITLE
Sign led light strip not dimmable

### ISSUE THREAD

**Issue by MNHPetersen** [athombv/com.tuya#35]
I have a Sign led light strip (WiFi) which is dimmable in the Tuya Smart app, but only have on/off attribute in Homey. What kind of information can I provide to help?

**Comment by bobvandevijver** [comment]
I believe this is fixed with the latest release. Can you please try, and if it doesn't, open a new ticket?

**Comment by MNHPetersen** [comment]
It still doesn’t work. I have tried to delete and add the light strip.
